<!DOCTYPE html>
<html>
<head>
	<style type="text/css">
		table {
			border: 1px solid black;
		}

		td {
			width: 200px;
			border: 1px solid black;
		}

		#messages {
			color: red;
		}
	</style>

	<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
	<script>
		$(document).ready(function() {
			var token = '';

			function displayLogin() {
				$('main').html(
					'<form><input id="user" type="text" placeholder="gebruikersnaam/email" ><input id="password" type="password" placeholder="password" ><input id="sign-in" type="button" value="sign in"><form>'
				);
			}

			function signin() {
				var user = $('#user').val(),
					pass = $('#password').val;

				$.get(
					'/token?email=' + user + '&password=' + pass
				).done(function(response) {
					token = response;
					display();
				});
			}

			function displayActionSearcher() {
				$('main').html(
					'<form><input id="search-input" type="text" placeholder="postcode"><input id="search" type="button" value="search"></form><table id="search-results"><thead><tr><td>id</td><td>postcode</td><td>initiator</td></tr></thead></table>'
				);
			}

			function searchAction() {
				var html = '<thead><tr><td>id</td><td>postcode</td><td>initiator</td></tr></thead>',
					postal = $('#search-input').val();

				$.get(
					'/actie?postalcode=' + postal

				).done(function(response) {
					html += '<tbody><tr id="' + 
					postal + 
					'" class="search-result"><td>' + 
					response.id + 
					'</td><td>' + 
					postal + 
					'</td><td>' + 
					response.intiatiefnemer + '</td></tr><tbody>';

					$('#messages').html('');

				}).fail(function(response) {
					$('#messages').html('could not find a action for the given postalcode!');

				}).always(function() {
					$('#search-results').html(html);					
				});
			}

			function displayAction(event) {

				var postal = event.currentTarget.id;

				$.get(
					'/actie?postalcode=' + postal	
				).done(function(response) {
					$('main').html(
						'<input id="goto-action-searcher" type="button" value="search action"><input id="join-action" type="button" value="join action"><table><tbody><tr><td>postalcode:</td><td>' + postal + '</td></tr><tr><td>initiator:</td><td>' + response.intiatiefnemer + '</td></tr></tbody></table><p>should show more data!</p>'
					);

				});
			}

			function joinAction() {
				alert('not implemented yet');
			}

			function activateAction() {
				alert('not implemented yet');
			}

			function display() {

				if(token == '')
					displayLogin();

				else
					displayActionSearcher();
			}

			$('body').on('click', '#sign-in', signin);
			$('body').on('click', '#search', searchAction);
			$('body').on('click', 'tr.search-result', displayAction);
			$('body').on('click', '#goto-action-searcher', displayActionSearcher);
			$('body').on('click', '#join-action', joinAction);

			display();
		});
	</script>
</head>

<body>

	<div id="messages"></div>

	<main>

	</main>

</body>
</html>